services:
  - type: web
    name: tendervault-api
    runtime: node
    env: node
    region: frankfurt 
    plan: free
    buildCommand: cd backend && npm install && npx prisma generate
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: USER_ACCESS_SECRET
        sync: false
    healthCheckPath: /
    autoDeploy: true
